name: Multi Job Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create a file
        run: echo "This is a dragon file" > dragon.txt
           
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
    
  test-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: ls -al