name: Build Docker Image and push to Docker Hub
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t awsdevops183/github-actions-demo:latest .

      - name: Push login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
           
      - name: Push docker image to DockerHub
        run: docker push awsdevops183/github-actions-demo:latest