name: Build Docker Image and push to Docker Hub
# on: [push, pull_request]
on:
  # schedule:
  #   - cron: '*/1 * * * *'  # Runs every 15 minutes
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [nginx:alpine, httpd:alpine]
    runs-on: ${{ matrix.os }}
    
    #runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t awsdevops183/github-actions-demo:latest .
      
      - name: Docker on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}

      # - name: Push login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ vars.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
           
      # - name: Push docker image to DockerHub
      #   run: docker push awsdevops183/github-actions-demo:latest